server:
  port: 8081


spring:
  application:
    name: "null4u"
  datasource:
    url: jdbc:mysql://3.37.180.207:3306/sesori?allowPublicKeyRetrieval=true
    username: root
    password: null4uproject

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
