server:
  port: 8081


spring:
  application:
    name: "null4u"
  datasource:
    url: jdbc:mysql://localhost:3306/database?allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
