server:
  port: 8081

spring:
  application:
    name: "null4u"
  config:
    import: classpath:/application-secrets.yml
  cors:
    allowed-origins: "http://localhost:5173"
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
